# Generated by Django 3.1.14 on 2022-07-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='fruits',
            options={'verbose_name_plural': 'Main table'},
        ),
    ]
